AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Alexa Skill
Resources:
 AlexaMetricSkill:
  Type: AWS::Serverless::Function
  Properties:
    Handler: vpa_alexa_skill.lambda_handler
    Runtime: python3.6
    Role: arn:aws:iam::209015279802:role/LambdaDynamoROle
    Timeout: 60
    CodeUri: s3://cf-templates-t9vckz1y2n2h-us-east-1/vpa_alexa_skill.zip
    Environment:
        Variables:
          greeting_msg: Welcome to the Voice Powered Analytics.  Please tell me what metrics you'd like to hear. To hear available metrics, ask Alexa tell me my metrics
          metrics_table: VPA_Metrics_Table
          exit_msg: Thank you for trying the Voice Powered Analytics.  Have a nice day!