---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPALambdaAthenaPoller:
    Type: "AWS::IAM::Role" 
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
             - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: "/"
  RolePolicies:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: vpa_lambda_athena_poller_permissions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: Stmt1506907773887
          Effect: Allow
          Action: 
            - cloudwatch:*
          Resource: 
            - "*"
        - Sid: Stmt1506907792079
          Effect: Allow
          Action: 
            - logs:*
          Resource: 
            - "*"
        - Sid: Stmt1506907804049
          Action: 
            - athena:*
          Effect: Allow
          Resource: 
            - "*"
        - Sid: Stmt1506907824634
          Action: 
            - xray:*
          Effect: Allow
          Resource: 
            - "*"
        - Sid: Stmt1506907846668
          Effect: Allow
          Action: 
            - s3:*
          Resource: 
            - "*"
        - Sid: Stmt1506907885059
          Action: 
            - dynamodb:*
          Effect: Allow
          Resource: 
            - "*"
        - Sid: Stmt1506908036515
          Effect: Allow
          Action: 
            - glue:*
          Resource: 
            - "*"
      Roles: [Ref: VPALambdaAthenaPoller]
  VPAAlexaSkill:
    Type: "AWS::IAM::Role" 
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
             - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: "/"
  RolePolicies:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: vpa_alexa_skill_permissions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: Stmt1506907773887
          Effect: Allow
          Action: 
            - cloudwatch:*
          Resource: 
            - "*"
        - Sid: Stmt1506907792079
          Effect: Allow
          Action: 
            - logs:*
          Resource: 
            - "*"
        - Sid: Stmt1506908036515
          Effect: Allow
          Action: 
            - dynamodb:putitem
            - dynamodb:scan
          Resource: 
            - "*"
      Roles: [Ref: VPAAlexaSkill]